### PR TITLE
Fix: Post-deploy produces confusing error #48

### LINKED ISSUE #48: Post-deploy produces confusing error
Steps to reproduce:

1. Define a component in the `hub.yaml` as follows

```yaml
components
- name: dex
  source:
    dir: components/dex
    git:
      remote: https://github.com/epam/kubeflow-components.git
      subDir: dex
  hooks:
  - file: bin/dex-post-deploy.sh
    triggers: [post-deploy]
```

2. Run `hubctl stack deploy:` 

> Note: post-deploy hook not exists!

4. See logs

```text
2023/06/09 00:56:56 Error: exec: no command
2023/06/09 00:56:56 One of post-deploy hooks failed. See logs
2023/06/09 00:56:56 Wrote state `/Users/akranga/kubeflow/semantic-search-infra/app-runtime/.hub/
```

Actual results:

1. There are no logs
2. Error message is misleading

Expected results:

1. Hubctl should not deploy proceed with the deployment if hooks not found. And fail with explicit error message

Rationale: Such deployment won't be successful in any case. Then the deployment should not be started

### PR DESCRIPTION
**Pull request by oginskis**
* if hook file can't be found: exit with an error
* if the hook file is found, but can't be executed because of permissions: exit with an error and recommend a user to run `chmod +x` against the hook

### CODE REVIEW

File: cmd/hub/lifecycle/deploy.go [hunk 1]
```diff
@@ -674,8 +674,9 @@ func fireHooks(trigger string, stackBaseDir string, component *manifest.Componen
 		var err error
 		script, err := findScript(hook.File, searchDirs...)
 		if err != nil || script == "" {
-			util.Warn("Unable to locate hook script `%s:` %v", hook.File, err)
-			continue
+			// script file not found
+			util.Warn("Error: Unable to locate hook script `%s:` %v", hook.File, err)
```
Comment (akranga) [inline cmd/hub/lifecycle/deploy.go:678]: Looks like 'log.Fatalf' is more appropriate

File: cmd/hub/lifecycle/deploy.go [hunk 2]
```diff
@@ -684,8 +685,9 @@ func fireHooks(trigger string, stackBaseDir string, component *manifest.Componen
 		}
 		stdout, stderr, err := delegateHook(script, stackBaseDir, component, componentParameters, osEnv)
 		if err != nil {
-			if strings.Contains(err.Error(), "fork/exec : no such file or directory") {
-				log.Printf("Error: file %s has not been found.", script)
+			// script found but can't be executed because of permissions
+			if strings.Contains(err.Error(), "permission denied") {
+				log.Printf("Error: Permission denied. Try chmod +x %s", script)
```
Comment (akranga) [inline cmd/hub/lifecycle/deploy.go]: Same comment as above. 
Error message might be misleading, because 'script' may not return exact script. See `probeScript` implementation. Therefore I would suggest fail with "permission denied (file not executable)" or something similar but more user friendly

Also "chmod" may confuse Windows users

**Review by akranga — CHANGES_REQUESTED** [review]

File: cmd/hub/lifecycle/deploy.go (hunk 2 above)
Comment (akranga) [reply cmd/hub/lifecycle/deploy.go]: A comment to @akranga  ... `Fatalf` is inappropriate here as will force `system.exit(1)`. Dropping first comment

Comment (oginskis) [reply cmd/hub/lifecycle/deploy.go]: Changed the error

Comment (TheRealSpaceShip) [reply cmd/hub/lifecycle/deploy.go]: I propose a message like: `error: Permission denied. Hook script "%s" should be executable`

**Review by akranga — CHANGES_REQUESTED** [review]
Please see the comment from @TheRealSpaceShip

**Review by TheRealSpaceShip — APPROVED** [review]
